FROM node:16-alpine

WORKDIR '/app'

COPY package.json .

RUN npm install

COPY . .                    

#COPY . . is deleted if we are using volumes to reference the source code in the local instead of inside the container, but in production it needs to be there

CMD [ "npm","run","start" ]